name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://orgab2fee26.crm4.dynamics.com'
        app-id: '059a7e3f-6eb0-4f1d-b265-c7c6b073cb67'
        client-secret: ${{ secrets.password }}
        tenant-id: '56ba767f-bc84-4565-8a33-0ee9e18236cc' 

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://orgab2fee26.crm4.dynamics.com'
        app-id: '059a7e3f-6eb0-4f1d-b265-c7c6b073cb67'
        password-secret: ${{ secrets.password }}
        solution-name: MagnusBranchTest
        solution-output-file: out/exported/ALMLab.zip
        client-secret: ${{ secrets.password }}
        tenant-id: '56ba767f-bc84-4565-8a33-0ee9e18236cc' 

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/MagnusBranchTest.zip
        solution-folder: out/solutions/MagnusBranchTest
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ALMLab
        solution-target-folder: solutions/ALMLab
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
